Added June 2021 Donation Information
CardanoMDP/Donations pull request #114
Opened 2021-08-01 18:01 UTC by RiseCardano

2021-08-11 14:32 UTC, kiriakos approved these changes
LGTM

2021-08-11 14:36 UTC, kiriakos requested changes

2021-08-11 14:36 UTC, kiriakos commented on RISE/donations.yml
> +    name: Water Aid UK
can you add the `contact` field please? Can be an email.

2021-08-11 14:36 UTC, kiriakos commented on RISE/donations.yml
> +    name: Save The Children
Here too, can you add the `contact` field please? Can be an email.

2022-02-11 03:00 UTC, aloopmarin007 commented
Please create a new updated PR , Thank you, We will close this one since it's out of date.

2022-02-11 03:00 UTC, closed without merging