AMOON first donation to Save The Children
CardanoMDP/Donations pull request #138
Opened 2021-08-18 00:56 UTC by adamoonpool

Please review and merge the changes.Thanks.

2021-08-22 20:29 UTC, ResponsibleStaking approved these changes

2021-08-22 20:30 UTC, ResponsibleStaking requested changes
Filename is incorrect. Please check and rename.

2021-08-24 18:24 UTC, adamoonpool commented
Fixed the file name issue. Pls review and approve.

2021-08-25 06:35 UTC, ResponsibleStaking approved these changes

2021-08-25 06:36 UTC, merged

2021-08-25 06:36 UTC, ResponsibleStaking commented
Thanks for updating. Approved and Merged!