ADABR
CardanoMDP/Donations pull request #179
Opened 2021-09-25 01:07 UTC by tauanbinato

Adding ADABR proof of donations.

2021-09-30 20:52 UTC, ResponsibleStaking requested changes

2021-09-30 20:52 UTC, ResponsibleStaking commented on ADABR/donations.yml
> +  announcement_url: https://www.instagram.com/p/CSwwplPNZ7z/
This is the same announcement_url as above. Propably a copy paste issue.

2021-10-18 18:49 UTC, tauanbinato commented
> Hi @tauanbinato ! Please give feedback to the above comment. I'd like to clean out old PRs.

Done, thanks

2022-02-12 16:27 UTC, nova4005 commented
Hey, I was checking this and the automated checks are failing for no 'tel' on some of your recipients. If you can add those in I can continue with the review.

2022-06-24 20:04 UTC, nova4005 commented
Closing this since we have not received a response. You can reopen once the updates are completed.

2022-06-24 20:04 UTC, closed without merging