Added SOLID and initial donation
CardanoMDP/Donations pull request #56
Opened 2021-05-10 21:23 UTC by jbradach

2021-05-14 12:03 UTC, kiriakos commented
Hi there! I'm trying to understand the intermediate transaction that You posted. This seems to be a transaction of 100Ada to a wallet staked to SOLID pool. How does this transaction fund a donation? Also, the PDF mentions an amount of ` $100 ADA` Is the donation in Dolars or in Ada?

2021-05-14 12:05 UTC, kiriakos commented
PS, who is the owner of this wallet? They have 9M unstaked and I would like to propose the delegate it towards MDP :-)

2021-05-25 16:35 UTC, jbradach commented
> Hi there! I'm trying to understand the intermediate transaction that You posted (tx cd6e6b1d94cd506e8ffb67c7b5ef440d318b6ed2316914131724e1d0193ddf34). This seems to be a transaction of 100Ada to a wallet staked to SOLID pool. How does this transaction fund a donation? Also, the PDF mentions an amount of ` $100 ADA` Is the donation in Dolars or in Ada?

Hello! Sorry for the delayed response. This donation of 100 ADA was made to a wallet controlled by the organization. They're new to cryptocurrency and this is the first contribution of this type they've received. The PDF mentioning dollars is a mistake since they received 100 ADA and at the time of the donation that was around $160.

The organization opted to keep the contribution as ADA and stake it back into the pool until they are prepared to convert it to USD at a later time.

2021-05-25 16:41 UTC, jbradach commented
> PS, who is the owner of this wallet? They have 9M unstaked and I would like to propose the delegate it towards MDP :-)

I'm not sure where you're seeing 9M unstaked. I don't have anything close to that in my wallets. One of wallet does have 10,000,000 SOLID, a governance token we created recently that we plan to use to allow delegators to vote on which projects we fund.

2021-06-19 07:10 UTC, kiriakos requested changes

2021-06-19 07:10 UTC, kiriakos commented on SOLID/donations.yml
> +  # ^ a list of files relating to the donation. Usualy photos or screenshots
Hmm... apparently the `yq` utility, which is being used by the CI to validate the file references, has a bug and returns the comments as well. Can you please remove the comments in lines 16-19?
Thanks

2021-07-03 06:43 UTC, jbradach reviewed
Comments have been removed.

2021-07-03 18:36 UTC, kiriakos approved these changes

2021-07-03 18:40 UTC, kiriakos approved these changes
lgtm

2021-07-13 22:45 UTC, ResponsibleStaking commented
Cant merge because of "This branch is out-of-date with the base branch".
Instructions here should help to update the branch to allow merging this PR: https://stackoverflow.com/questions/53712930/how-to-fix-this-in-git-this-branch-is-out-of-date-with-the-base-branch

2021-08-12 07:25 UTC, kiriakos commented
@jbradach I had the same issue with a couple other PRs and here is a writeup of what I did that allowed the PRs to be merged. #129 Can we try that?

2021-09-03 14:33 UTC, closed without merging