Create Donations
CardanoMDP/Donations pull request #86
Opened 2021-07-06 18:53 UTC by Golden-VS

2021-07-09 22:09 UTC, ResponsibleStaking requested changes

2021-07-09 22:09 UTC, ResponsibleStaking commented on A4G/Donations
> +  ada: 2145 # <- These must be numbers. Can be decimals though. See below
I beliefe you miss a comma here

2021-07-09 22:09 UTC, ResponsibleStaking commented on A4G/Donations
> +  timestamp: 1599026880
This timestamp reflects the 2.9.2020, which is 10 months ago. Please re-check

2021-07-09 22:09 UTC, ResponsibleStaking commented on A4G/Donations
> +    - TICKR/2020-09-02-TGB.png
Please create file references inside your Pool Folder A4G/...

2021-07-09 22:09 UTC, ResponsibleStaking commented on A4G/Donations
> +    - TICKR/2020-09-02-photo-of-delivery.png
same here

2021-07-09 22:09 UTC, ResponsibleStaking commented on A4G/Donations
> +
Remove or fill out these optional attributes.
Generally all comments above can be removed.

2021-07-16 18:17 UTC, kiriakos approved these changes
LGTM

2021-07-16 18:24 UTC, kiriakos commented
Thanks @ResponsibleStaking for pointing the PR in the right direction. All requested changes have been done.

@Golden-VS since you are donating via adapay it would be awesome if you can also include the ada transaction in intermediate txs next time. This way people can see your donation on chain. While it is not mandated by our process, it would go a long way in regards to trustworthiness if we who do crypto based donations do that.

2021-07-16 19:12 UTC, ResponsibleStaking approved these changes
Looks all good. As mentioned adding the TX ID would be good for next time!

2021-07-16 19:14 UTC, merged