Even Moar Donations!
CardanoMDP/Donations pull request #88
Opened 2021-07-09 19:51 UTC by StakeWithPride

Several new ones so I'm finally caught up.

2021-07-09 22:00 UTC, ResponsibleStaking requested changes
Invalid YAML Structure. Please update

2021-07-09 22:00 UTC, ResponsibleStaking commented on PRIDE/donations.yml
> +  recipient: MBARARA RISE FOUNDATION
This is not valid against YAML conventions.
If you only want to use this recipient once you can just delete the name in this line.
If you want to reuse it you can give it a name like &mbaara and reuse it in later donations later with *mbaara
When reusing you will not need the sub-attributes (name, contact, ..)

2021-07-09 22:00 UTC, ResponsibleStaking commented on PRIDE/donations.yml
> +  recipient: LGBT+ Rights Ghana
Same Issue as above

2021-07-09 22:00 UTC, ResponsibleStaking commented on PRIDE/donations.yml
> +  recipient: LGBT VOICE TANZANIA
same

2021-07-09 22:00 UTC, ResponsibleStaking commented on PRIDE/donations.yml
> +  recipient: All Out
Same

2021-07-09 22:00 UTC, ResponsibleStaking commented on PRIDE/donations.yml
> +  recipient: Iranti
Same

2021-07-10 21:05 UTC, StakeWithPride commented
Thanks for the feedback. I've updated the yaml by removing the name attribute. Thanks for your guidance.

2021-07-13 22:34 UTC, ResponsibleStaking approved these changes

2021-07-13 22:34 UTC, merged